version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_GENERIC_TIMEZONE=America/Sao_Paulo
      - WEBHOOK_TUNNEL_URL=${WEBHOOK_TUNNEL_URL}
    volumes:
      - ./data:/home/node/.n8n
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http n8n:5678
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
    - "4040:4040" 
    depends_on:
      - n8n

volumes:
  data:
  wa_data: